name: dyplom
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: 
  intl: ^0.16.1
  google_sign_in: ^4.5.4
  cupertino_icons: ^0.1.3
  avatar_glow: ^1.2.0
  easy_localization: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/fruit-tree.png
    - assets/images/poland.png
    - assets/images/united-kingdom.png
    - assets/translations/
  fonts:
  - family: Quicksand
    fonts:
      - asset: assets/fonts/Quicksand-Regular.ttf
      - asset: assets/fonts/Quicksand-Bold.ttf
        weight: 700